baseURL = 'https://avrillaecw.github.io/'
languageCode = 'id-id'
title = 'Avrilla | IT Specialist & Master Student'
theme = 'PaperMod'

[params]
    name = "Avrilla"
    description = "S2 Teknologi Informasi UGM | Pranata Komputer"
    author = "Avrilla"
    analytics = { google = { fingerprint = "" } }

[params.profileMode]
    enabled = true
    title = "Hi there, I'm Avrilla 👋"
    subtitle = "S2 IT UGM Student | Computer Specialist (Pranata Komputer)"
    imageUrl = "link_foto_kamu.jpg" # Opsional
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://linkedin.com/in/username-mu"
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/avrillaecw"

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "Portofolio"
        url = "/posts/"
        weight = 10